import "./styles/main.scss"
import "./assets/img/logo.png"
import "./assets/img/rectangulo-301.png"
import "./assets/img/Rectángulo 303.png"
import "./assets/img/Rectángulo -10.png"
import "./assets/img/Rectángulo -11.png"
import "./assets/img/rectangulo-1.png"
import "./assets/img/rectangulo-2.png"
import "./assets/img/rectangulo-3.png"
import "./assets/img/rectangulo-4.png"
import "./assets/img/rectangulo-5.png"
import "./assets/img/rectangulo-6.png"
import "./assets/img/rectangulo-7.png"
import "./assets/img/rectangulo-8.png"
import "./assets/img/rectangulo-9.png"
import "./assets/img/rectangulo-1.png"
import "./js/filtro"
import "./js/search"

